version: '3'

services:
    web:
        build: .
        command: gunicorn project.wsgi:application --bind 0.0.0.0:80 --workers 4
        volumes:
            - .:/code
        ports:
            - 80:80
